# This file is *NOT* reloaded automatically when you use 'jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
title: LabPlus
description: Government Service Innovation Lab
url: https://serviceinnovationlab.github.io
baseurl: ""

defaults:
  -
    scope:
      path: "" # means “all files”
    values:
      layout: default
